import { Activity, CheckCircle2, CircleDollarSign, FileText, Flag, ShieldCheck, Users } from 'lucide-react'
import { requests, providers, services } from '../data/mockData'
import { StatusBadge } from '../components/StatusBadge'

export function AdminDashboard({ section }: { section: string }) {
  if (section === 'requests') return <AdminRequests />
  if (section === 'providers') return <AdminProviders />
  if (section === 'services') return <AdminServices />
  if (section === 'customers') return <AdminCustomers />
  if (section === 'settings') return <AdminSettings />
  return <AdminHome />
}

function AdminHome() {
  return <div className="workspaceDashboard"><div className="workspaceWelcome"><div><span className="eyebrow">OPERATIONS</span><h1>ANYwork marketplace.</h1><p>Monitor requests, providers and platform activity from one place.</p></div><button className="buttonPrimary">Review requests</button></div><div className="metricRow"><Metric label="Open requests" value="24" note="8 awaiting quotes" icon={<FileText />} /><Metric label="Providers" value="86" note="71 verified" icon={<Users />} /><Metric label="GMV this month" value="$94k" note="+12% vs last month" icon={<CircleDollarSign />} /><Metric label="Completed jobs" value="312" note="98% completed on time" icon={<CheckCircle2 />} /></div><div className="adminGridModern"><section className="dashboardCard"><CardHeading eyebrow="NEEDS ATTENTION" title="Operations queue" /><div className="adminQueue">{requests.map((request) => <div className="adminQueueRow" key={request.id}><span className="requestId">{request.id}</span><div><strong>{request.title}</strong><small>{request.customer} · {request.providerId ? providers.find((p) => p.id === request.providerId)?.name : 'No provider yet'}</small></div><StatusBadge status={request.status} /><strong>{'$' + request.budget.toLocaleString()}</strong></div>)}</div></section><section className="dashboardCard"><CardHeading eyebrow="PLATFORM HEALTH" title="Marketplace signals" /><div className="healthModern"><span><ShieldCheck /> 86 verified providers</span><span><Activity /> 98% response rate</span><span><Flag /> 3 disputes need review</span><span><CheckCircle2 /> 312 completed jobs</span></div></section></div><section className="dashboardCard"><CardHeading eyebrow="REQUESTS BY STATUS" title="Marketplace flow" /><div className="adminBars">{['Requested','Quoted','Scheduled','In Progress','Completed'].map((status) => { const count = requests.filter((request) => request.status === status).length; const width = Math.max(14, count * 18); return <div key={status}><span>{status}</span><div><i style={{ width: width + '%' }} /></div><strong>{count}</strong></div> })}</div></section></div>
}

function AdminRequests() { return <div className="workspaceDashboard"><PageTitle kicker="OPERATIONS" title="Service requests" description="Track requests across the marketplace lifecycle." /><div className="tableCard">{requests.map((request) => <div className="tableRowModern" key={request.id}><span className="requestId">{request.id}</span><div><strong>{request.title}</strong><small>{request.customer} · {request.location}</small></div><span>{request.date}</span><StatusBadge status={request.status} /><strong>{'$' + request.budget.toLocaleString()}</strong></div>)}</div></div> }
function AdminProviders() { return <div className="workspaceDashboard"><PageTitle kicker="DIRECTORY" title="Providers" description="Manage provider profiles, verification and marketplace visibility." /><div className="providerAdminGrid">{providers.map((provider) => <div className="providerAdminCard" key={provider.id}><div className="providerAvatarLarge">{provider.initials}</div><div><strong>{provider.name}</strong><span>{provider.location}</span><small>{provider.completedJobs} jobs · {provider.rating} rating</small></div><span className="adminVerified"><ShieldCheck size={13} /> Verified</span></div>)}</div></div> }
function AdminServices() { return <div className="workspaceDashboard"><PageTitle kicker="CATALOG" title="Services" description="Keep the marketplace service catalog focused and understandable." /><div className="adminServiceGrid">{services.map((service) => <div className="adminServiceCard" key={service.id}><span className="eyebrow">{service.title}</span><h3>{service.label}</h3><p>{service.description}</p><strong>{'Starting ' + service.startingPrice}</strong></div>)}</div></div> }
function AdminCustomers() { return <div className="workspaceDashboard"><PageTitle kicker="CUSTOMERS" title="Customers" description="Monitor customer accounts and active work." /><div className="customerAdminGrid">{['John Doe','ABC Business','Retail Co.','Office Group'].map((name) => <div className="customerAdminCard" key={name}><div className="smallAvatar">{name.slice(0,2).toUpperCase()}</div><div><strong>{name}</strong><span>Active account</span></div><small>Recent activity</small></div>)}</div></div> }
function AdminSettings() { return <div className="workspaceDashboard"><PageTitle kicker="PLATFORM" title="Settings" description="Define marketplace rules and moderation controls." /><div className="marketTwoColumn"><div className="dashboardCard"><h2>Marketplace controls</h2><Toggle label="Require provider verification" /><Toggle label="Allow customer reviews" checked /><Toggle label="Provider messaging" checked /><Toggle label="Quote comparison" checked /></div><div className="dashboardCard"><h2>Lifecycle</h2><p className="cardMuted">Requested → Quoted → Scheduled → In Progress → Completed</p><button className="buttonSecondary">Manage statuses</button></div></div></div> }
function Toggle({ label, checked=false }: { label: string; checked?: boolean }) { return <label className="toggleModern"><span>{label}</span><input type="checkbox" defaultChecked={checked} /></label> }
function Metric({ label,value,note,icon }: { label:string; value:string; note:string; icon:React.ReactNode }) { return <div className="metricCard"><div className="metricIcon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></div> }
function CardHeading({ eyebrow,title }: { eyebrow:string; title:string }) { return <div className="cardHeading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div></div> }
function PageTitle({ kicker,title,description }: { kicker:string; title:string; description:string }) { return <div className="workspacePageTitle"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{description}</p></div> }