import type { ReactNode } from 'react'
import { ArrowRight, BriefcaseBusiness, CheckCircle2, ChevronRight, Clock3, DollarSign, MessageCircle, PackageCheck, Plus, Star, Users } from 'lucide-react'
import { providers, requests, services } from '../data/mockData'
import { StatusBadge } from '../components/StatusBadge'
import type { AnyWorkProfile } from '../types/auth'

export function ProviderDashboard({ section, profile, onNavigate }: { section: string; profile: AnyWorkProfile; onNavigate: (path: string) => void }) {
  if (section === 'requests') return <ProviderRequests onNavigate={onNavigate} />
  if (section === 'jobs') return <ProviderJobs onNavigate={onNavigate} />
  if (section === 'services') return <ProviderServices />
  if (section === 'earnings') return <ProviderEarnings />
  if (section === 'messages') return <ProviderMessages />
  return <ProviderHome profile={profile} onNavigate={onNavigate} />
}

function ProviderHome({ profile, onNavigate }: { profile: AnyWorkProfile; onNavigate: (path: string) => void }) {
  const incoming = requests.filter((request) => request.status === 'Requested' || request.status === 'Quoted')
  const businessName = profile.company_name || profile.display_name || 'Your business'
  return <div className="workspaceDashboard"><div className="workspaceWelcome experienceWelcome providerWelcome"><div><span className="eyebrow">PROVIDER HOME</span><h1>Welcome, {businessName}.</h1><p>Manage your pipeline, respond to new work and keep customers updated.</p></div><button className="buttonPrimary" onClick={() => onNavigate('/provider/services')}><Plus size={17} /> Manage services</button></div><div className="metricRow"><Metric label="New requests" value="4" note="Need your response" icon={<Clock3 />} /><Metric label="Active jobs" value="8" note="Across 6 locations" icon={<PackageCheck />} /><Metric label="This month" value="$18.4k" note="Before payouts" icon={<DollarSign />} /><Metric label="Rating" value="4.9" note="96 reviews" icon={<Star />} /></div><div className="dashboardGrid"><section className="dashboardCard wide"><CardHeading eyebrow="OPPORTUNITIES" title="Requests worth reviewing" action="View all" onClick={() => onNavigate('/provider/requests')} />{incoming.map((request) => <button className="requestRowModern" key={request.id} onClick={() => onNavigate('/provider/requests/' + request.id)}><div><span className="requestId">{request.id}</span><strong>{request.title}</strong><small>{request.customer} · {request.location} · {request.date}</small></div><StatusBadge status={request.status} /><ChevronRight size={16} /></button>)}</section><section className="dashboardCard"><CardHeading eyebrow="TODAY" title="Schedule" /><div className="providerSchedule"><Schedule time="09:00" title="Banner installation" meta="Retail Co. · Parramatta" /><Schedule time="13:30" title="Site inspection" meta="ABC Business · Alexandria" /><Schedule time="16:00" title="Furniture assembly" meta={businessName + ' · North Sydney'} /></div></section><section className="dashboardCard"><CardHeading eyebrow="PIPELINE" title="Request lifecycle" /><div className="miniPipeline">{['Requested','Quoted','Scheduled','In Progress','Completed'].map((status) => <div key={status}><span>{status}</span><strong>{requests.filter((request) => request.status === status).length}</strong></div>)}</div></section><section className="dashboardCard wide"><CardHeading eyebrow="CUSTOMER EXPERIENCE" title="Keep your profile strong" /><div className="profileHealth"><div><CheckCircle2 /><strong>Verified profile</strong><span>Visible to customers</span></div><div><Star /><strong>4.9 rating</strong><span>96 reviews</span></div><div><MessageCircle /><strong>98% response</strong><span>Strong marketplace signal</span></div><div><Users /><strong>184 jobs</strong><span>Completed successfully</span></div></div></section></div></div>
}

function ProviderRequests({ onNavigate }: { onNavigate: (path: string) => void }) { return <div className="workspaceDashboard"><PageTitle kicker="REQUESTS" title="Service requests" description="Review incoming work and send clear quotes." /><div className="workspaceToolbar"><div className="searchField"><input placeholder="Search customer, service or request ID..." /></div><button className="buttonSecondary">Filter</button></div><div className="tableCard">{requests.map((request) => <button className="tableRowModern" key={request.id} onClick={() => onNavigate('/provider/requests/' + request.id)}><span className="requestId">{request.id}</span><div><strong>{request.title}</strong><small>{request.customer} · {request.location}</small></div><span>{request.date}</span><StatusBadge status={request.status} /><strong>{'$' + request.budget.toLocaleString()}</strong><ChevronRight size={16} /></button>)}</div></div> }
function ProviderJobs({ onNavigate }: { onNavigate: (path: string) => void }) { return <div className="workspaceDashboard"><PageTitle kicker="ACTIVE WORK" title="Jobs" description="Track scheduled, active and completed jobs." /><div className="tableCard">{requests.filter((request) => ['Scheduled','In Progress','Completed'].includes(request.status)).map((request) => <button className="tableRowModern" key={request.id} onClick={() => onNavigate('/provider/jobs/' + request.id)}><span className="requestId">{request.id}</span><div><strong>{request.title}</strong><small>{request.customer} · {request.location}</small></div><span>{request.date}</span><StatusBadge status={request.status} /><strong>{request.providerId ? 'Assigned' : 'Open'}</strong><ChevronRight size={16} /></button>)}</div></div> }
function ProviderServices() { return <div className="workspaceDashboard"><PageTitle kicker="MY SERVICES" title="Services you offer" description="Control which services customers can request from your business." /><div className="serviceWorkspaceGrid">{providers[1].serviceIds.map((id) => { const service = services.find((item) => item.id === id)!; return <div className="serviceWorkspaceCard" key={id}><div className="serviceCardIcon"><BriefcaseBusiness size={21} /></div><span className="eyebrow">{service.title}</span><h3>{service.label}</h3><p>{service.description}</p><div><strong>{'From ' + service.startingPrice}</strong><button className="buttonSecondary">Edit</button></div></div> })}<div className="serviceWorkspaceCard addService"><Plus size={24} /><h3>Add a service</h3><p>Expand your service area and reach more customers.</p><button className="buttonPrimary">Add service</button></div></div></div> }
function ProviderEarnings() { return <div className="workspaceDashboard"><PageTitle kicker="EARNINGS" title="Revenue" description="Understand completed work, open quotes and upcoming payments." /><div className="metricRow"><Metric label="This month" value="$18,420" note="14 completed jobs" icon={<DollarSign />} /><Metric label="Awaiting payment" value="$2,640" note="3 invoices" icon={<Clock3 />} /><Metric label="Open quotes" value="$7,900" note="6 opportunities" icon={<BriefcaseBusiness />} /><Metric label="Completed" value="184" note="All time" icon={<PackageCheck />} /></div><div className="tableCard invoiceTable"><div className="tableHead"><span>Invoice</span><span>Customer</span><span>Amount</span><span>Status</span></div>{['INV-1027','INV-1021','INV-1018','INV-1015'].map((id,index) => <div className="invoiceTableRow" key={id}><span>{id}</span><span>{['Retail Co.','John Doe','ABC Business','Office Group'][index]}</span><strong>{['$1,850','$920','$640','$1,240'][index]}</strong><StatusBadge status={index === 0 ? 'Quoted' : 'Completed'} /></div>)}</div></div> }
function ProviderMessages() { return <div className="workspaceDashboard"><PageTitle kicker="MESSAGES" title="Customer messages" description="Keep all customer conversations attached to the job." /><div className="chatModern"><div className="chatModernHeader"><strong>AW-1027 · John Doe</strong><StatusBadge status="In Progress" /></div><div className="chatBubble incoming">Hi, can you arrive around 10 AM instead?</div><div className="chatBubble outgoing">Yes. I have updated the appointment to 10 AM.</div><div className="chatBubble incoming">Perfect, thank you.</div><div className="chatComposer"><input placeholder="Write a message..." /><button className="buttonPrimary">Send</button></div></div></div> }
function Metric({ label, value, note, icon }: { label: string; value: string; note: string; icon: ReactNode }) { return <div className="metricCard"><div className="metricIcon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></div> }
function CardHeading({ eyebrow, title, action, onClick }: { eyebrow: string; title: string; action?: string; onClick?: () => void }) { return <div className="cardHeading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action && <button className="textLink" onClick={onClick}>{action}<ArrowRight size={15} /></button>}</div> }
function Schedule({ time, title, meta }: { time: string; title: string; meta: string }) { return <div className="providerScheduleRow"><b>{time}</b><div><strong>{title}</strong><span>{meta}</span></div><StatusBadge status="Scheduled" /></div> }
function PageTitle({ kicker, title, description }: { kicker: string; title: string; description: string }) { return <div className="workspacePageTitle"><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{description}</p></div> }
