import { useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, Clock3, MapPin, MessageCircle, Star } from 'lucide-react'
import { quotes, requests, providers, services } from '../data/mockData'
import { StatusBadge } from '../components/StatusBadge'
import { ProviderCard } from '../components/ProviderCard'

export function RequestDetailPage({ requestId, onBack, onNavigate }: { requestId: string; onBack: () => void; onNavigate: (path: string) => void }) {
  const request = requests.find((item) => item.id === requestId) || requests[0]
  const [tab, setTab] = useState<'quotes' | 'updates'>('quotes')
  const requestQuotes = request.quotes.map((id) => quotes.find((quote) => quote.id === id)).filter(Boolean)
  const service = services.find((item) => item.id === request.serviceId)
  return <div className="workspaceDashboard">
    <button className="backLinkModern" onClick={onBack}><ArrowLeft size={15} /> Back to requests</button>
    <div className="requestDetailTop"><div><span className="requestId">{request.id}</span><h1>{request.title}</h1><p>{request.location} · {request.date}</p></div><StatusBadge status={request.status} /></div>
    <div className="requestHeroMeta"><div><MapPin size={16} /><span>{request.location}</span></div><div><CalendarDays size={16} /><span>{request.date}</span></div><div><strong>{'$' + request.budget.toLocaleString()}</strong><span>Customer budget</span></div><div><strong>{service?.title}</strong><span>Service</span></div></div>
    <div className="requestMainGrid"><div>
      <div className="requestTabsModern"><button className={tab === 'quotes' ? 'active' : ''} onClick={() => setTab('quotes')}>Quotes ({requestQuotes.length})</button><button className={tab === 'updates' ? 'active' : ''} onClick={() => setTab('updates')}>Updates</button></div>
      {tab === 'quotes' ? <div className="quoteComparison">{requestQuotes.length ? requestQuotes.map((quote) => { const provider = providers.find((item) => item.id === quote?.providerId)!; return <div className="quoteCardModern" key={quote?.id}><div className="quoteProvider"><ProviderCard provider={provider} compact /><span className="quoteAmount">{'$' + quote?.amount.toLocaleString()}</span></div><p>{quote?.message}</p><div className="quoteMeta"><span><CalendarDays size={14} /> {quote?.availability}</span><span><Star size={14} /> {provider.rating}</span><span><CheckCircle2 size={14} /> {provider.completedJobs} jobs</span></div><div className="quoteActions"><button className="buttonSecondary" onClick={() => onNavigate('/providers/' + provider.id)}>View provider</button><button className="buttonPrimary">Accept quote <ArrowRight size={16} /></button></div></div> }) : <div className="emptyModern"><h3>Waiting for provider responses</h3><p>Providers matching this request will appear here.</p></div>}</div> : <div className="updatesTimeline"><TimelineItem title="Request submitted" done /><TimelineItem title="Providers are reviewing the job" done /><TimelineItem title="Quote responses received" done={request.status !== 'Requested'} /><TimelineItem title="Appointment scheduled" done={['Scheduled','In Progress','Completed'].includes(request.status)} /><TimelineItem title="Work in progress" done={['In Progress','Completed'].includes(request.status)} /><TimelineItem title="Completed & ready for review" done={request.status === 'Completed'} /></div>}
    </div><aside><div className="sideCard"><span className="eyebrow">YOUR REQUEST</span><h3>What you asked for</h3><p>{request.description}</p><div className="sideDetail"><span>Provider</span><strong>{request.providerId ? providers.find((item) => item.id === request.providerId)?.name : 'Waiting for quotes'}</strong></div><div className="sideDetail"><span>Budget</span><strong>{'$' + request.budget.toLocaleString()}</strong></div><div className="sideActions"><button className="buttonSecondary" onClick={() => onNavigate('/customer/messages')}><MessageCircle size={15} /> Message</button><button className="buttonPrimary">Edit request</button></div></div><div className="sideCard"><span className="eyebrow">NEED HELP?</span><h3>ANYwork support</h3><p>Your request, messages and updates stay together so you know what happens next.</p><button className="textLink">Open support <ArrowRight size={15} /></button></div></aside></div>
  </div>
}
function TimelineItem({ title, done }: { title: string; done: boolean }) { return <div className={'timelineModernItem ' + (done ? 'done' : '')}><div>{done ? <CheckCircle2 size={15} /> : <Clock3 size={15} />}</div><span>{title}</span></div> }