import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {ArrowRight,CheckCircle2,Clock3,MapPin,MessageCircle,Paperclip,Plus,CalendarDays,FileText,BriefcaseBusiness,Users,Settings,LayoutDashboard,ChevronRight,Upload,Menu, X, Star, Hammer, Printer, Wrench, Boxes, HardHat} from "lucide-react";
import "./styles.css";

const services=[
 {id:"print",title:"Print",sub:"Printing & signage",icon:Printer,items:["Banner & tarpaulin printing","Business & site signage","Window graphics","Promotional materials"]},
 {id:"build",title:"Build",sub:"Furniture & fabrication",icon:Hammer,items:["Custom furniture","Cabinets & counters","Shelving & storage","Custom fixtures"]},
 {id:"install",title:"Install",sub:"Installation & assembly",icon:Boxes,items:["Banner installation","Sign installation","Furniture assembly","Display installation"]},
 {id:"maintain",title:"Maintain",sub:"Handyman & maintenance",icon:Wrench,items:["Minor repairs","Painting & patching","Fixture replacement","Property maintenance"]},
 {id:"site",title:"Site",sub:"Site services",icon:HardHat,items:["Site preparation","Fit-out assistance","Material handling","Site coordination"]},
 {id:"custom",title:"Custom",sub:"Special projects",icon:BriefcaseBusiness,items:["Custom jobs","Event setup","Special fabrication","Other work"]},
];

const jobs=[{id:"AW-1025",name:"Banner Installation",status:"Scheduled",date:"24 Sep 2026",location:"Parramatta",value:"$1,850"},{id:"AW-1024",name:"Office Furniture Assembly",status:"Quote Sent",date:"27 Sep 2026",location:"North Sydney",value:"$920"}];

function App(){
 const [mode,setMode]=useState("customer"),[page,setPage]=useState("home"),[mobile,setMobile]=useState(false),[quote,setQuote]=useState(false),[step,setStep]=useState(1),[selected,setSelected]=useState(""),[sent,setSent]=useState(false);
 const nav=mode==="customer"?["home","services","jobs","quotes","messages"]:["dashboard","jobs","quotes","customers","schedule","projects","invoices","messages"];
 const title=page==="home"?"Got a job that needs doing?":page==="services"?"Services":page==="jobs"?"My Jobs":page==="quotes"?"Quotes":page==="messages"?"Messages":page==="dashboard"?"Operations Dashboard":page[0]?.toUpperCase()+page.slice(1);
 const go=p=>{setPage(p);setMobile(false)};
 const submit=()=>{setSent(true);setStep(4)};
 return <div className="app">
  <header className="topbar"><div className="brand" onClick={()=>go(mode==="customer"?"home":"dashboard")}><span className="brandMark">AW</span><span>ANYwork</span></div><nav className="desktopNav">{nav.slice(0,5).map(n=><button className={page===n?"active":""} onClick={()=>go(n)} key={n}>{n==="home"?"Home":n[0].toUpperCase()+n.slice(1)}</button>)}</nav><div className="topActions"><button className="modeBtn" onClick={()=>{setMode(mode==="customer"?"admin":"customer");setPage(mode==="customer"?"dashboard":"home")}}>{mode==="customer"?"Customer":"Admin"} <ChevronRight size={15}/></button><button className="iconBtn mobileOnly" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
  {mobile&&<div className="mobileNav">{nav.map(n=><button onClick={()=>go(n)} key={n}>{n[0].toUpperCase()+n.slice(1)}</button>)}</div>}
  <main>
   {mode==="customer" ? <Customer page={page} title={title} go={go} quote={quote} setQuote={setQuote} step={step} setStep={setStep} selected={selected} setSelected={setSelected} sent={sent} submit={submit}/> : <Admin page={page} go={go}/>}
  </main>
  <footer><strong>ANYwork Services</strong><span>Print. Build. Install. Maintain.</span><span>Literally any work.</span></footer>
 </div>
}

function Customer({page,go,quote,setQuote,step,setStep,selected,setSelected,sent,submit}){
 if(quote)return <QuoteWizard step={step} setStep={setStep} selected={selected} setSelected={setSelected} sent={sent} submit={submit} close={()=>{setQuote(false);setStep(1);setSent(false)}}/>;
 if(page==="services")return <Services onQuote={()=>setQuote(true)}/>;
 if(page==="jobs")return <Jobs/>;
 if(page==="quotes")return <Quotes onQuote={()=>setQuote(true)}/>;
 if(page==="messages")return <Messages/>;
 return <><section className="hero"><div><div className="eyebrow">ANYWORK SERVICES</div><h1>Got a job that<br/><em>needs doing?</em></h1><p>Tell us what you need. From printing and fabrication to installation, maintenance and site services, we work out the solution.</p><div className="actions"><button className="primary" onClick={()=>setQuote(true)}>Request a Quote <ArrowRight size={18}/></button><button className="secondary" onClick={()=>go("services")}>Explore Services</button></div><div className="trust"><CheckCircle2/> Clear quotes <CheckCircle2/> Job tracking <CheckCircle2/> Before & after photos</div></div><div className="heroCard"><div className="heroCardTop"><span>ANY JOB</span><span className="dot"></span></div><h3>Tell us what you need.</h3><p>Upload photos, add your location and preferred date. We'll review it and prepare a quote.</p><button onClick={()=>setQuote(true)}>Start a request <ArrowRight size={16}/></button></div></section>
 <section className="section"><div className="sectionHead"><div><div className="eyebrow">WHAT WE DO</div><h2>One team. Many services.</h2></div><button className="textBtn" onClick={()=>go("services")}>View all services <ArrowRight size={16}/></button></div><div className="serviceGrid">{services.map(s=><ServiceCard key={s.id} service={s} onClick={()=>setQuote(true)}/>)}</div></section>
 <section className="split"><div><div className="eyebrow">HOW IT WORKS</div><h2>From request to done.</h2><div className="steps"><Step n="01" t="Request a quote" d="Describe the job and add photos."/><Step n="02" t="Review & approve" d="We prepare a clear quotation."/><Step n="03" t="Schedule the work" d="Pick a suitable date and location."/><Step n="04" t="Track completion" d="See updates, photos and your invoice."/></div></div><div className="darkPanel"><span className="eyebrow">YOUR NEXT JOB</span><h3>Start with a photo.</h3><p>Don't know which service you need? That's okay. Show us the job and we'll help identify the right service.</p><button className="primary light" onClick={()=>setQuote(true)}>Tell us about it <ArrowRight size={17}/></button></div></section></>;
}

function ServiceCard({service,onClick}){const I=service.icon;return <button className="serviceCard" onClick={onClick}><div className="serviceIcon"><I size={22}/></div><h3>{service.title}</h3><p>{service.sub}</p><span>{service.items.slice(0,2).join(" • ")}</span><ArrowRight className="cardArrow" size={18}/></button>}
function Services({onQuote}){return <section className="section pageSection"><div className="eyebrow">OUR SERVICES</div><h1>Print. Build. Install.<br/>Maintain.</h1><p className="lead">Choose a service or simply tell us what you need. ANYwork can handle custom jobs too.</p><div className="serviceGrid">{services.map(s=><ServiceCard key={s.id} service={s} onClick={onQuote}/>)}</div><div className="customBanner"><div><span className="eyebrow">NOT SURE?</span><h2>Something else?</h2><p>Send us the details. We'll work out the right approach.</p></div><button className="primary" onClick={onQuote}>Request a Quote <ArrowRight size={18}/></button></div></section>}
function Jobs(){return <section className="section pageSection"><div className="eyebrow">CUSTOMER PORTAL</div><h1>My Jobs</h1><p className="lead">Track every request from quote to completion.</p><div className="jobList">{jobs.map(j=><div className="jobCard" key={j.id}><div className="jobMain"><span className="jobId">{j.id}</span><h3>{j.name}</h3><p><MapPin size={15}/> {j.location} &nbsp; • &nbsp; <CalendarDays size={15}/> {j.date}</p></div><div className="jobStatus"><span className={j.status==="Scheduled"?"status green":"status amber"}>{j.status}</span><strong>{j.value}</strong></div><div className="progress"><span style={{width:j.status==="Scheduled"?"72%":"48%"}}/></div></div>)}</div></section>}
function Quotes({onQuote}){return <section className="section pageSection"><div className="eyebrow">QUOTES</div><h1>Your Quotes</h1><div className="quoteRow"><div><span className="jobId">AW-1025</span><h3>Banner Installation</h3><p>Valid until 30 Sep 2026</p></div><div><strong>$1,850</strong><span className="status amber">Pending approval</span></div><button className="primary small" onClick={onQuote}>View quote</button></div><button className="secondary" onClick={onQuote}>Request another quote</button></section>}
function Messages(){return <section className="section pageSection"><div className="eyebrow">MESSAGES</div><h1>ANYwork Support</h1><div className="chat"><div className="message them">Hi! How can we help with your job?</div><div className="message me">Can you arrive around 10 AM instead?</div><div className="message them">Yes, we've updated your appointment.</div><div className="chatInput">Type a message... <button className="primary small">Send</button></div></div></section>}
function Step({n,t,d}){return <div className="step"><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div></div>}
function QuoteWizard({step,setStep,selected,setSelected,sent,submit,close}){return <section className="wizard"><div className="wizardHead"><div><div className="eyebrow">REQUEST A QUOTE</div><h1>{sent?"Request received.":"Tell us about the job."}</h1></div><button className="iconBtn" onClick={close}><X/></button></div>{sent?<div className="success"><CheckCircle2 size={56}/><h2>We've got it.</h2><p>Your request has been submitted. We'll review the details and contact you with the next steps.</p><div className="requestId">REQUEST #AW-1026</div><button className="primary" onClick={close}>Back to dashboard</button></div>:<><div className="wizardSteps"><span className={step>=1?"on":""}>01 Service</span><span className={step>=2?"on":""}>02 Details</span><span className={step>=3?"on":""}>03 Photos & contact</span></div>{step===1&&<div className="wizardBody"><h2>What do you need?</h2><p>Choose one or select Other if you're not sure.</p><div className="optionGrid">{services.map(s=><button className={selected===s.id?"option selected":"option"} key={s.id} onClick={()=>setSelected(s.id)}><s.icon size={22}/><span>{s.title}</span><small>{s.sub}</small></button>)}</div><div className="wizardActions"><button className="primary" disabled={!selected} onClick={()=>setStep(2)}>Continue <ArrowRight size={17}/></button></div></div>}{step===2&&<div className="wizardBody"><h2>Describe the job</h2><p>More detail helps us prepare the right quote.</p><textarea placeholder="Tell us what you need..."></textarea><div className="formGrid"><input placeholder="Preferred date"/><input placeholder="Job location"/></div><div className="wizardActions"><button className="secondary" onClick={()=>setStep(1)}>Back</button><button className="primary" onClick={()=>setStep(3)}>Continue <ArrowRight size={17}/></button></div></div>}{step===3&&<div className="wizardBody"><h2>Add photos & contact details</h2><p>Photos, measurements or reference images are welcome.</p><div className="upload"><Upload size={24}/><strong>Drop photos here or click to upload</strong><span>JPG, PNG up to 10MB each</span></div><div className="formGrid"><input placeholder="Full name"/><input placeholder="Phone number"/><input placeholder="Email address"/><input placeholder="Preferred contact method"/></div><div className="wizardActions"><button className="secondary" onClick={()=>setStep(2)}>Back</button><button className="primary" onClick={submit}>Submit Request <ArrowRight size={17}/></button></div></div>}</div>}</section>}

function Admin({page,go}){const stats=[["NEW REQUESTS","8",LayoutDashboard],["QUOTES","5",FileText],["ACTIVE JOBS","12",BriefcaseBusiness],["COMPLETED","16",CheckCircle2]];return <section className="admin"><aside><div className="sideBrand"><span className="brandMark">AW</span><b>ANYwork</b></div><div className="sideLabel">OPERATIONS</div>{["dashboard","jobs","quotes","customers","schedule","projects","invoices","messages"].map(n=><button className={page===n?"sideActive":""} onClick={()=>go(n)} key={n}>{n==="dashboard"?<LayoutDashboard/>:n==="jobs"?<BriefcaseBusiness/>:n==="quotes"?<FileText/>:n==="customers"?<Users/>:n==="schedule"?<CalendarDays/>:n==="projects"?<Boxes/>:n==="invoices"?<FileText/>:<MessageCircle/>}{n[0].toUpperCase()+n.slice(1)}</button>)}<button><Settings/>Settings</button></aside><div className="adminContent"><div className="adminHeader"><div><div className="eyebrow">OPERATIONS</div><h1>{page==="dashboard"?"Good morning, ANYwork":"Manage "+page}</h1></div><button className="primary">+ New Job</button></div>{page==="dashboard"?<><div className="stats">{stats.map(([a,b,I])=><div className="stat" key={a}><I/><span>{a}</span><strong>{b}</strong></div>)}</div><div className="adminGrid"><div className="panel"><div className="panelHead"><h2>Today's Schedule</h2><span>21 Sep 2026</span></div>{["Banner Installation","Furniture Delivery","Site Inspection","Sign Installation"].map((x,i)=><div className="scheduleRow" key={x}><time>{["08:00","10:30","13:00","15:30"][i]}</time><div><strong>{x}</strong><span>{["Parramatta","North Sydney","Alexandria","Mascot"][i]}</span></div><span className="status green">{i<2?"Scheduled":"Pending"}</span></div>)}</div><div className="panel"><div className="panelHead"><h2>Recent Requests</h2><span>View all</span></div>{["Furniture","Signage","Printing","Maintenance"].map((x,i)=><div className="requestRow" key={x}><span>AW-10{25-i}</span><strong>{x}</strong><span className="status amber">{["New","Quoted","Scheduled","New"][i]}</span></div>)}</div></div></>:<div className="panel emptyPanel"><BriefcaseBusiness size={42}/><h2>{page[0].toUpperCase()+page.slice(1)}</h2><p>The {page} workspace is ready for the next implementation phase.</p></div>}</div></section>}
createRoot(document.getElementById("root")).render(<App/>);